-- Example schema for the Tren Engine demo

create table if not exists facebook (
  id bigint generated by default as identity primary key,
  topic text,
  platform text,
  posts numeric,
  views numeric,
  engagement_score numeric,
  trend_velocity numeric,
  growth_pct numeric,
  status text,
  created_at timestamptz default now()
);

create table if not exists twitter (
  id bigint generated by default as identity primary key,
  topic text,
  platform text,
  posts numeric,
  views numeric,
  engagement_score numeric,
  trend_velocity numeric,
  growth_pct numeric,
  status text,
  created_at timestamptz default now()
);

create table if not exists instagram (
  id bigint generated by default as identity primary key,
  topic text,
  platform text,
  posts numeric,
  views numeric,
  engagement_score numeric,
  trend_velocity numeric,
  growth_pct numeric,
  status text,
  created_at timestamptz default now()
);

create table if not exists tiktok (
  id bigint generated by default as identity primary key,
  topic text,
  platform text,
  posts numeric,
  views numeric,
  engagement_score numeric,
  trend_velocity numeric,
  growth_pct numeric,
  status text,
  created_at timestamptz default now()
);

-- Seed sample rows (optional)
-- insert into facebook (topic, platform, posts, views, engagement_score, trend_velocity, growth_pct, status)
-- values ('#DoubleBlinkChallenge', 'Facebook', 1820, 245000, 18450, 6.3, 38, 'breaking');
